name: sbti_test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.1=py_0
  - python=3.7.8=h60c2a47_1_cpython
  - pip:
    - nose2==0.9.2
    - six==1.15.0
    - Sphinx==3.0.3
    - sphinx-autodoc-typehints==1.10.3
    - git+https://github.com/OFBDABV/sphinx-autoapi.git
    - sphinx-rtd-theme==0.4.3
    - pandas==1.0.3
    - xlrd==1.2.0
